
import { Movie } from './types';

export const MOVIES: Movie[] = [
  {
    id: '1',
    title: 'Inception',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    thumbnailUrl: 'https://picsum.photos/seed/inception/400/600',
    backdropUrl: 'https://picsum.photos/seed/inception-bg/1200/600',
    genre: ['Sci-Fi', 'Action'],
    duration: '2h 28m',
    rating: 'PG-13',
    year: 2010,
    type: 'movie',
    origin: 'hollywood',
    popularity: 98
  },
  {
    id: '2',
    title: 'Dilwale Dulhania Le Jayenge',
    description: 'When Raj meets Simran in Europe, it isn\'t love at first sight but when Simran moves to India for an arranged marriage, love makes its presence felt.',
    thumbnailUrl: 'https://picsum.photos/seed/ddlj/400/600',
    backdropUrl: 'https://picsum.photos/seed/ddlj-bg/1200/600',
    genre: ['Romance', 'Drama'],
    duration: '3h 10m',
    rating: 'U',
    year: 1995,
    type: 'movie',
    origin: 'bollywood',
    popularity: 95
  },
  {
    id: '3',
    title: 'The Dark Knight',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    thumbnailUrl: 'https://picsum.photos/seed/darkknight/400/600',
    backdropUrl: 'https://picsum.photos/seed/darkknight-bg/1200/600',
    genre: ['Action', 'Crime'],
    duration: '2h 32m',
    rating: 'PG-13',
    year: 2008,
    type: 'movie',
    origin: 'hollywood',
    popularity: 99
  },
  {
    id: '4',
    title: '3 Idiots',
    description: 'Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently.',
    thumbnailUrl: 'https://picsum.photos/seed/3idiots/400/600',
    backdropUrl: 'https://picsum.photos/seed/3idiots-bg/1200/600',
    genre: ['Comedy', 'Drama'],
    duration: '2h 50m',
    rating: 'U/A',
    year: 2009,
    type: 'movie',
    origin: 'bollywood',
    popularity: 97
  },
  {
    id: '5',
    title: 'Stranger Things',
    description: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.',
    thumbnailUrl: 'https://picsum.photos/seed/stranger/400/600',
    backdropUrl: 'https://picsum.photos/seed/stranger-bg/1200/600',
    genre: ['Sci-Fi', 'Horror'],
    duration: '4 Seasons',
    rating: 'TV-14',
    year: 2016,
    type: 'series',
    origin: 'hollywood',
    popularity: 96
  },
  {
    id: '6',
    title: 'Sacred Games',
    description: 'A link in their pasts leads an honest cop to a fugitive gang lord, whose cryptic warning spurs the officer on a quest to save Mumbai from cataclysm.',
    thumbnailUrl: 'https://picsum.photos/seed/sacred/400/600',
    backdropUrl: 'https://picsum.photos/seed/sacred-bg/1200/600',
    genre: ['Crime', 'Thriller'],
    duration: '2 Seasons',
    rating: 'TV-MA',
    year: 2018,
    type: 'series',
    origin: 'bollywood',
    popularity: 92
  },
  {
    id: '7',
    title: 'Interstellar',
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    thumbnailUrl: 'https://picsum.photos/seed/interstellar/400/600',
    backdropUrl: 'https://picsum.photos/seed/interstellar-bg/1200/600',
    genre: ['Sci-Fi', 'Adventure'],
    duration: '2h 49m',
    rating: 'PG-13',
    year: 2014,
    type: 'movie',
    origin: 'hollywood',
    popularity: 94
  },
  {
    id: '8',
    title: 'Lagaan',
    description: 'In Victorian India, a small village stakes its future on a game of cricket against their ruthless British rulers.',
    thumbnailUrl: 'https://picsum.photos/seed/lagaan/400/600',
    backdropUrl: 'https://picsum.photos/seed/lagaan-bg/1200/600',
    genre: ['Drama', 'Sports'],
    duration: '3h 44m',
    rating: 'U',
    year: 2001,
    type: 'movie',
    origin: 'bollywood',
    popularity: 93
  },
  {
    id: '9',
    title: 'Breaking Bad',
    description: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.',
    thumbnailUrl: 'https://picsum.photos/seed/breaking/400/600',
    backdropUrl: 'https://picsum.photos/seed/breaking-bg/1200/600',
    genre: ['Crime', 'Drama'],
    duration: '5 Seasons',
    rating: 'TV-MA',
    year: 2008,
    type: 'series',
    origin: 'hollywood',
    popularity: 100
  },
  {
    id: '10',
    title: 'Dangal',
    description: 'Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression.',
    thumbnailUrl: 'https://picsum.photos/seed/dangal/400/600',
    backdropUrl: 'https://picsum.photos/seed/dangal-bg/1200/600',
    genre: ['Action', 'Biography'],
    duration: '2h 41m',
    rating: 'U',
    year: 2016,
    type: 'movie',
    origin: 'bollywood',
    popularity: 96
  }
];
